#!/bin/bash

shopt -s extglob

for f in $(find ./originals -type f)
do
	echo "Processing file $f";
	DIR="$(dirname $f | awk '{ print substr ($0, 13)}')"/;
	if [ $DIR = "/" ]
	then
		DIR=""
	fi
	mkdir -p ./normalized/$DIR
	ffmpeg-normalize $f \
		-ar 48000 \
		-c:a libopus \
		-ofmt opus \
		-o normalized/$DIR$(basename $f)
done
